a = complex(5, 8)
b = complex(4, -7)
print ("\n Sean dos numero complejos a: \n")
print (a)
print ("\n y b: \n")
print(b)
print("\n La suma de dos complejos es: \n")
print(a+b)
print("\n El producto de dos complejos es: \n")
print(a*b)
print("\n La parte real del complejo a es: \n")
print(a.real)
print("\n La magnitud del complejo a es: \n")
print(abs(a))

print("\n El complejo conjugado del complejo a es: : \n")
print(a.conjugate())
